spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/weather_test_db
    username: sa
    password:
    driverClassName: org.h2.Driver

private:
  open-weather-map:
    key: 4455d224d1b0230a8995a2760040811e
  weather-api:
    key: 56001a90422c4f86ab7123554221802