spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:weather_test_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
server:
  error:
    include-message: always

private:
  open-weather-map:
    key: 4455d224d1b0230a8995a2760040811e
  weather-api:
    key: 56001a90422c4f86ab7123554221802
  weather-bit:
    key: 23c5f8a60b39492d95158ff3d4605bde
  cities: London,GB Moscow,RU Tyumen,RU
  schedule: 0 0 10 * * *
